---
- name: webserver setup
  hosts: "webservers"
  become: true

  tasks:
  - name: copy website data
    copy:
      src: ./www
      dest: /var/

  - name: copy webserver binary
    copy:
      src: ./target/release/server
      dest: /usr/local/bin/translate-webserver
      mode: 0755

  - name: create systemd service file
    template:
      src: ./server-systemd-service-template.j2
      dest: /etc/systemd/system/translate-webserver.service

  - name: reload systemd
    systemd:
      daemon_reload: yes

  - name: enable and start systemd service
    systemd:
      name: translate-webserver
      state: started
      enabled: yes
