---
- name: webserver setup
  hosts: "webservers"
  become: true

  tasks:
  - name: create etc folder
    file:
      path: /etc/translate-webserver
      state: directory
      mode: 0755

  - name: copy google credentials
    copy:
      src: ../google_credentials.json
      dest: /etc/translate-webserver/google_credentials.json
      mode: 0400

  - name: copy website data
    copy:
      src: ./www
      dest: /var/

  - name: copy webserver binary
    copy:
      src: ./target/release/server
      dest: /usr/local/bin/translate-webserver
      mode: 0755

  - name: create systemd service file
    template:
      src: ./server-systemd-service-template.j2
      dest: /etc/systemd/system/translate-webserver.service

  - name: reload systemd
    systemd:
      daemon_reload: yes

  - name: enable and (re)start systemd service
    systemd:
      name: translate-webserver
      state: restarted
      enabled: yes
